# Generated by Django 4.1.5 on 2023-01-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_user_blogmodel_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='aproved',
            field=models.BooleanField(default=False, verbose_name='Aproved'),
        ),
    ]
