# Generated by Django 4.1.5 on 2023-01-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blogmodel_aproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='aproved',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
